[doc]
name = 'rendu'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'repas'
type = 'pdf'
shell_escape = true
preamble = ''
index = '../pdfs/repas.tex'
postamble = ''